#### meta_baseline
train_dataset: image-bongard-ldmqry
train_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_train.json
  split: train
  augment_plus: true
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  use_DEKR: True
  det_thresh: 0.8
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

val_seen_obj_seen_act_dataset: image-bongard-bbox
val_seen_obj_seen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_val_seen_obj_seen_act.json
  split: val
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  det_thresh: 0.8
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

val_seen_obj_unseen_act_dataset: image-bongard-bbox
val_seen_obj_unseen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_val_seen_obj_unseen_act.json
  split: val
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  det_thresh: 0.8
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

val_unseen_obj_seen_act_dataset: image-bongard-bbox
val_unseen_obj_seen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_val_unseen_obj_seen_act.json
  split: val
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  det_thresh: 0.8
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

val_unseen_obj_unseen_act_dataset: image-bongard-bbox
val_unseen_obj_unseen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_val_unseen_obj_unseen_act.json
  split: val
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  det_thresh: 0.8
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

test_seen_obj_seen_act_dataset: image-bongard-bbox
test_seen_obj_seen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_test_seen_obj_seen_act.json
  split: test
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

test_seen_obj_unseen_act_dataset: image-bongard-bbox
test_seen_obj_unseen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_test_seen_obj_unseen_act.json
  split: test
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

test_unseen_obj_seen_act_dataset: image-bongard-bbox
test_unseen_obj_seen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_test_unseen_obj_seen_act.json
  split: test
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

test_unseen_obj_unseen_act_dataset: image-bongard-bbox
test_unseen_obj_unseen_act_dataset_args:
  im_dir: ../assets/data/hake/images
  split_file: ./cache/bongard_hoi_test_unseen_obj_unseen_act.json
  split: test
  bbox_file: ./cache/hico_faster_rcnn_R_101_DC5_3x_objectness.pkl
  human_det_file: ./cache/DEKR/DEKR_det_bongard.pkl
  human_det_thres: 0.3
  iou_thres: 0.6

use_gt_bbox: false
cts_lambda: 0.3
subspace_loss_lambda: 0.03

teach_model: my_model_teach
teach_model_args:
  encoder: raw_bbox_encoder
  encoder_args: {encoder: resnet50, use_boxes_dim: False}
  method: cosine
  type: raw

stud_model: my_model_stud
stud_model_args:
  encoder: raw_bbox_encoder
  encoder_args: {encoder: resnet50, use_boxes_dim: False}
  method: cosine
  type: raw

load_encoder: ./cache/resnet50-{}.pth
encoder_pretrain: imagenet



n_way: 2
n_shot: 6
n_query: 1
train_batches: 100000
ep_per_batch: 8  ## in total, if you use multiple GPU, this value is the sum of all GPU's batch size

max_epoch: 4
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4, 'milestones': [50, 80]}

visualize_datasets: true
ets: true

print_freq: 10
save_epoch: 1
eval_epoch: 1
